

FOOTBALLERS = [
    {
        "name": "Lionel Messi",
        "nationality": "Argentina",
        "club": "Inter Miami",
        "position": "Forward",
        "image_url": "https://www.parismatch.com/lmnr/var/pm/public/media/image/Lionel-Messi_0.jpg?VersionId=9IMsjKtwh3CF1p7sEXw_D0hvR0g.h51e.jpg",
    },
    {
        "name": "Cristiano Ronaldo",
        "nationality": "Portugal",
        "club": "Al Nassr",
        "position": "Forward",
        "image_url": "https://cdn.britannica.com/73/234573-050-8EE03E16/Cristiano-Ronaldo-ceremony-rename-airport-Santa-Cruz-Madeira-Portugal-March-29-2017.jpg",
    },
    {
        "name": "Kylian Mbappé",
        "nationality": "France",
        "club": "Real Madrid",
        "position": "Forward",
        "image_url": "https://imageio.forbes.com/specials-images/imageserve/626c7cf3616c1112ae834a2b/0x0.jpg?format=jpg&crop=1603,1603,x1533,y577,safe&height=416&width=416&fit=bounds.jpg",
    },
    {
        "name": "Erling Haaland",
        "nationality": "Norway",
        "club": "Manchester City",
        "position": "Forward",
        "image_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTWaZi4yh1ghlzyHNEk6ASJZZebqEPC203_9xxKWysWvxtvrrewlXJKruURz3BTsY9lhOGHdSi-tSMxaCZwXaw5zIc5MIIRIGcBwCACXPQ&s=10.jpg",
    },
    {
        "name": "Mohamed Salah",
        "nationality": "Egypt",
        "club": "Liverpool",
        "position": "Forward",
        "image_url": "https://img.a.transfermarkt.technology/portrait/big/148455-1727337594.jpg?lm=1.jpg",
    },
    {
        "name": "Vinicius Jr",
        "nationality": "Brazil",
        "club": "Real Madrid",
        "position": "Forward",
        "image_url": "https://cdn.britannica.com/45/273345-050-7B263FB8/Vinicius-Junior-Real-Madrid-football-soccer-player-UEFA-league-knockout--play-off-against-Manchester-City-2024-25.jpg",
    },
    {
        "name": "Jude Bellingham",
        "nationality": "England",
        "club": "Real Madrid",
        "position": "Midfielder",
        "image_url": "https://imageio.forbes.com/specials-images/imageserve/660cd0543bf4cc56969b3c75/0x0.jpg?format=jpg&crop=932,933,x312,y54,safe&height=416&width=416&fit=bounds.jpg",
    },
    {
        "name": "Kevin De Bruyne",
        "nationality": "Belgium",
        "club": "Manchester City",
        "position": "Midfielder",
        "image_url": "https://img.a.transfermarkt.technology/portrait/big/88755-1713391485.jpg?lm=1.jpg",
    },
    {
        "name": "Harry Kane",
        "nationality": "England",
        "club": "Bayern Munich",
        "position": "Forward",
        "image_url": "https://img.a.transfermarkt.technology/portrait/big/132098-1700211169.jpg?lm=1.jpg",
    },
    {
        "name": "Robert Lewandowski",
        "nationality": "Poland",
        "club": "Barcelona",
        "position": "Forward",
        "image_url": "https://b.fssta.com/uploads/application/soccer/headshots/2100.png",
    },
    {
        "name": "Lamine Yamal",
        "nationality": "Spain",
        "club": "Barcelona",
        "position": "Forward",
        "image_url": "https://img.a.transfermarkt.technology/portrait/big/937958-1773173768.jpg?lm=1.jpg",
    },
    {
        "name": "Pedri",
        "nationality": "Spain",
        "club": "Barcelona",
        "position": "Midfielder",
        "image_url": "https://i.pinimg.com/736x/0a/93/5e/0a935e57823545afe0658546bd59470e.jpg",
    },
    {
        "name": "Antoine Griezmann",
        "nationality": "France",
        "club": "Atletico Madrid",
        "position": "Forward",
        "image_url": "https://img.a.transfermarkt.technology/portrait/big/125781-1775233998.jpg?lm=1.jpg",
    },
    {
        "name": "Achraf Hakimi",
        "nationality": "Morocco",
        "club": "PSG",
        "position": "Defender",
        "image_url": "https://www.lequipe.fr/_medias/img-photo-jpg/forme-au-real-madrid-passe-par-le-borussia-dortmund-et-l-inter-milan-hakimi-a-ete-recrute-par-le-p/1500000001546606/12:347,1896:2231-828-828-75/95889.jpg",
    },
    {
        "name": "Bukayo Saka",
        "nationality": "England",
        "club": "Arsenal",
        "position": "Forward",
        "image_url": "https://ichef.bbci.co.uk/ace/standard/1104/cpsprodpb/fe88/live/2b714c20-b19a-11ef-9049-eda50882c74d.jpg",
    },
    {
        "name": "Phil Foden",
        "nationality": "England",
        "club": "Manchester City",
        "position": "Midfielder",
        "image_url": "https://img.a.transfermarkt.technology/portrait/big/406635-1668524492.jpg?lm=1",
    },
    {
        "name": "Rodri",
        "nationality": "Spain",
        "club": "Manchester City",
        "position": "Midfielder",
        "image_url": "https://img.a.transfermarkt.technology/portrait/big/357565-1682587890.jpg?lm=1",
    },
    {
        "name": "Raphinha",
        "nationality": "Brazil",
        "club": "Barcelona",
        "position": "Forward",
        "image_url": "https://img.a.transfermarkt.technology/portrait/big/411295-1729754479.png?lm=1",
    },
    {
        "name": "Virgil van Dijk",
        "nationality": "Netherlands",
        "club": "Liverpool",
        "position": "Defender",
        "image_url": "https://b.fssta.com/uploads/application/soccer/headshots/3575.png",
    },
    {
        "name": "Neymar Jr",
        "nationality": "Brazil",
        "club": "Al Hilal",
        "position": "Forward",
        "image_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR2xAxF0IEv5OecH6-5OljF_4G68TxnAP8bFIphx2C7VRKizo_-LVEZ423v&s=10",
    },
]
